### ISSUE TITLE
Test _read_background and _read_constants in _excel2dict

### ISSUE THREAD

**Issue by berland** [equinor/fmu-tools#104]
Code testing coverage tool reveals that two  functions in _excel2dict are not tested. These functions are probably important enough that we should have test code for them:

https://codecov.io/gh/equinor/fmu-tools/src/9018f73b831c4613c3d17120b204990ce69485f6/src/fmu/tools/sensitivities/_excel2dict.py

**Comment by mferrera** [comment]
Issue cleanup :) I believe #107 resolved
