### ISSUE TITLE
getting fraction per zone as a statistics for discrete parameter

### ISSUE THREAD

**Issue by miroine** [equinor/fmu-tools#111]
fraction per zone for discrete parameter is very useful (example: sand percentage for each zone), is it possible to include that in the `QCProperties `class (or is it there and I missed it ?) 
`xtgeo` has quite nice well class called `._get_fraction_per_zone()`   that I have used before ? how can we incorporate that in the qcproperties ?

**Comment by tnatt** [comment]
Hi @miroine, that should be possible with existing functionality. Just add the discrete Facies/NTG parameter as a property and add the Zone parameter as a selector. The trick is that you need to add a disc=True argument for the method that writes out the csv. 

This functionality was added a bit later, and I realize not documented properly... will make a note of that :) 
Please test and see if it works as you expect! Thanks

![image](https://user-images.githubusercontent.com/61694854/107647154-1f7d1380-6c7b-11eb-8d70-5c7ebe10d9ab.png)

**Comment by tnatt** [comment]
To improve user-friendliness I will change the code to make the disc=True argument redundant when properties of the same type (discrete or continuous) are used as input 👍
