### ISSUE TITLE
[create_rft_ertobs] Allow for different well trajectory name from RMS

### ISSUE THREAD

**Issue by mareco701** [equinor/fmu-tools#113]
https://github.com/equinor/fmu-tools/blob/ad3d23a7cded38b221186ee89581a7a21e2055b8/src/fmu/tools/rms/create_rft_ertobs.py#L139

RMS by default sets the trajectory name to ‘Imported trajectory’ when the trajectory is not made in RMS.
And then the script fails since it expects 'Drilled trajectory'.
Could it be possible to set the 'trajectory name' as a variable (input argument to the function) ?

**Comment by berland** [comment]
Can this be a global option (in the setup for the script), or is individual control pr. well needed?

**Comment by berland** [comment]
ping @JiZur

**Comment by mareco701** [comment]
I guess there could be different names of well trajectory for different wells but in theory all the wells with rft data should have been given the same well trajectory name...
