### ISSUE TITLE
Inter-dependencies in fmu.tools

### ISSUE THREAD

**Issue by berland** [equinor/fmu-tools#116]
https://github.com/equinor/fmu-tools/blob/ad3d23a7cded38b221186ee89581a7a21e2055b8/src/fmu/tools/__init__.py#L5

This line implies that a lot of things must be in place for fmu.tools to work. I am unsure whether it is a good idea to load so much in `__init__.py`. 

This is a recent error that is triggered by this line 
![image](https://user-images.githubusercontent.com/306834/108202196-09f76600-7121-11eb-9883-34d56d948079.png)

The fix for this error is to deploy the h5py library to the RMS 12.1 Python environment, the fact that this library is required for `rmsvolumetrics2csv` means that we are loading a lot of unneeded stuff into memory on script invocation.

**Comment by berland** [comment]
Ping @jriv, @tnatt, @JiZur

**Comment by jcrivenaes** [comment]
I don't see the __init__ file as a problem. The issue is that 12.1 python env is beta and h5py and friends were not installed there, which I can fix soon (.e.g xtgeo would no work either)
