### ISSUE TITLE
Documentation: qcproperties

### ISSUE THREAD

**Issue by bkhegstad** [equinor/fmu-tools#123]
Some comments on the documentation for qcproperties

1. The general name for the functions in qcforward is check() – which makes sens since one is checking stuff. For qcproperties I find it strange that 5 out of 8 examples got check() while the remaining 3 got extract_statistics() which is a better name
2.	One uses the names Geo**G**rid and Sim**G**rid in all examples except one where Geogrid and Simgrid is used. (“Comparison of data from different sources”)
3.	Wildcards for well name is great. But there is not much explanation. I would like to have a sentence explaining that a dot a star and a dollar (.\*$) means “the rest of the string can be anything”. I guess the dot is important for telling the system that wildcards are coming? Are there other wildcards to use too ?  (^*.)  or (.?.) or can general regex-syntax be used?
4.	The final setup with everything defined in a single yml-file is good. But to better see the structure (for those not that familiar with python dict vs yml) it could be useful if the yaml-file did exactly the same (or more) as the example above (“Example below collects statistical data from four different sources” )

**Comment by tnatt** [comment]
@bkhegstad thanks for your input 👍, I agree with your points! I am in the process of refactoring the code, and will take your comments into account when updating the documentation :)
