### ISSUE TITLE
Unnecessary pass statement

### ISSUE THREAD

**Issue by berland** [equinor/fmu-tools#125]
https://github.com/equinor/fmu-tools/blob/182050f0fb496f6ff00f87cfb04e5c502fe14f30/src/fmu/tools/rms/set_data_constant.py#L8

https://lgtm.com/projects/g/equinor/fmu-tools/snapshot/27042ecb99ddef098a0de81d51bca693d2481b2d/files/src/fmu/tools/rms/set_data_constant.py?sort=name&dir=ASC&mode=heatmap#x1d6028690f191ec:1

**Comment by mferrera** [comment]
File was removed
