### ISSUE TITLE
Updates for examples used in fmu-tools documentation

### ISSUE THREAD

**Issue by iainashepherd** [equinor/fmu-tools#127]
**qcforward functions**

1) Compare well zonation vs well (Example when ran inside RMS with different settings for wells)

- "gridzones": [ZONEGRIDNAME]      believe this should be        "gridprops": [ZONEGRIDNAME]
- mode: "write"    /    mode: "append"      should be     "mode": "write"    /   "mode": "append"
- Script fails if qc folder doesn't exist or file named "well_vs_grid.csv" doesn't exist
- Not correctly reporting SET1 or SET2 stats to file.

2) Grid Quality Indicators (Example when ran inside RMS)

- qcf.run(usedata, project=project)     believe this should be     QCJOB.run(usedata, project=project)
- mode: "write"     should be    "mode": "write"  
- Script fails if qc folder doesn't exist or file named "gridquality.csv" doesn't exist

3) Running grid_statistics  (Example when executed inside RMS (More settings)

- "path": PATH,   should be     "path": "PATH",

**The qcproperties class**

1) Examples scripts
- Scripts do not compute anything in RMS when completed - should these not at least say "Done"?

**The qcreset module**

1) set_data_constant examples (something similar probably needed for set_data_empty examples?)
- from fmu.tools import qcreset     should be    from fmu.tools.rms import set_data_constant as qcreset

**Comment by JiZur** [comment]
The last point will be corrected with the PR as the file containing the code is renamed into qcreset. So the import: "from fmu.tools.rms import qcreset" should work fine
