### ISSUE TITLE
Add more general Sw functions as python functions

### ISSUE THREAD

**Issue by jcrivenaes** [equinor/fmu-tools#208]
RMS supports mostly Leverett J functions on the standard form, as

$$
S_w = A(X \cdot h)^B
$$

where $Xh$ is the Leverett J function (simple og full)

However, there are cases where the formulation is

$$
S_w = A(M + X \cdot h)^B
$$

There are also other variants, e.g. Brooks-Corey and BVW which needs to be supported. They can all be written on the latter form, where $Xh$ have other formulation than Leverett J.

**Comment by mferrera** [comment]
Closed with #209
