### ISSUE TITLE
Observation file format conversion entrypoint

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/fmu-tools#58]
Add a new commandline entrypoint with one purpose:

Convert back and forth between the following obs.formats:
- YAML format (e.g. the one used by `fmu-ensemble`).
- ERT obs.file format
- ResInsight obs.file format.

The YAML format is the most rich of them, allowing general metadata. I.e. conversion from YAML to one of the other formats will result in not all metainformation being transferred, but that is perfectly fine due to:
- People can then simply maintain the YAML format in practice, and "down scale" to the others when need to update.
- At some point in time they all will hopefully support the same YAML format (that format might be slightly different from todays `fmu.ensemble` format, but then the same commandline entrypoint can be used to also convert to the agreed format).

**Comment by berland** [comment]
Check that a configsuite template can be written for the YAML syntax. If there are conflicts between the current fmu-ensemble yaml syntax and configsuite, we can consider adapting fmu-ensemble to it.

https://configsuite.readthedocs.io/en/stable/

**Comment by anders-kiaer** [comment]
Could be a good thing to do, but not 100% sure in this case compared to more standard data schema. What are the benefits with `configsuite` in this context? We use configsuite in e.g. FlowNet, to configure the FlowNet software run settings. Here however we are more "data oriented", compared to "configuration oriented".

Long term maybe observation data is automatically available as JSON from some data base/source API. I.e. a good alternative could be a simple standard JSON schema (for the YAML obs. file), and validation using https://pypi.org/project/jsonschema/ (when we are in the Python world, and some NodeJS package when some day we move to http-web).

**Comment by berland** [comment]
You might be right it is not so relevant here. Having it considered was many only suggestion, and now it has been considered :+1:
