### ISSUE TITLE
test_qcproperties is failing

### ISSUE THREAD

**Issue by berland** [equinor/fmu-tools#76]
https://github.com/equinor/fmu-tools/blob/3aa6d5218b1780be5d24e728397f20ec1ea68843/tests/test_qcproperties/test_qcproperties_wells.py#L51

This test now fails CI, dependency change? (xtgeo?)

`FAILED tests/test_qcproperties/test_qcproperties_wells.py::test_full_dataframe_wells - assert 0.15833842959785524 == 0.1534 ± 1.0e-03`

**Comment by tnatt** [comment]
will look into it now @berland

**Comment by tnatt** [comment]
Closed in #77
